//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadaverExquisito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int id_comentario { get; set; }
        public int id_usuario { get; set; }
        public int id_historia { get; set; }
        public Nullable<int> mg { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> numero_caracteres { get; set; }
    
        public virtual Historia Historia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
