//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadaverExquisito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia
    {
        public Historia()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int id_historia { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<int> numero_caracteres { get; set; }
    
        public virtual ICollection<Comentario> Comentario { get; set; }
    }
}
