//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadaverExquisito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> mg_dados { get; set; }
        public Nullable<int> mg_obtenidos { get; set; }
        public string usuario1 { get; set; }
        public string contraseña { get; set; }
    
        public virtual ICollection<Comentario> Comentario { get; set; }
    }
}
